catalog/urls.py
from django.conf.urls import url, patterns, include
from catalog import views

urlpatterns = patterns('',
                       url(r'^product_add_to_cart/(?P<pk>[\d]+)/$', views.ProductAddToCart.as_view(), name='add_to_cart'),
                       url(r'^product/(?P<category_slug>[-\w]+(/[\w-]+)*)/(?P<slug>[-\w]+)/', views.ProductDetailView.as_view(), name='product'),
                       url(r'^(?P<slug>[\w-]+(/[\w-]+)*)/', views.CategoryDetailView.as_view(), name='category'),
                       )

clavutich/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from clavutich.views import IndexView, WriteToUsView
from django.conf.urls.static import static
from django.contrib.flatpages import views
from clavutich import settings

from django.contrib.sitemaps.views import sitemap
from clavutich.sitemaps import StaticViewSitemap
from catalog.sitemaps import CategorySitemap, ProductSitemap
from extend_flatpages.sitemaps import ExtendFlatPage
from django.views.decorators.cache import cache_page

sitemaps = {
    'static': StaticViewSitemap,
    'flat_pages': ExtendFlatPage,
    'category': CategorySitemap,
    'product': ProductSitemap,
}

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^catalog/', include('catalog.urls', app_name='catalog', namespace='catalog')),
    url(r'^cart/', include('easy_cart.urls', app_name='easy_cart', namespace='easy_cart')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^select2/', include('django_select2.urls')),
]

urlpatterns += [
    url(r'^about-us/$', views.flatpage, {'url': '/about-us/'}, name='about'),
    url(r'^contacts/$', views.flatpage, {'url': '/contacts/'}, name='contacts'),
    url(r'^svyazatsya-s-nami/', WriteToUsView.as_view(), name='write_to_us'),
    url(r'^(?P<url>.*/)$', views.flatpage),
    url(r'^sitemap\.xml$', cache_page(24*60*60)(sitemap), {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                           document_root=settings.STATIC_ROOT)

easy_cart/urls.py
__author__ = 'igor'
from django.conf.urls import url
from easy_cart.views import ShowView, OrderView, RemoveProduct, UpdateQuantityProductView

urlpatterns = [
    url(r'^$', ShowView.as_view(), name='show'),
    url(r'^remove/(?P<pk>[\d]+)/$', RemoveProduct.as_view(), name='remove'),
    url(r'^order/$', OrderView.as_view(), name='order'),
    # url(r'^make_order/$', SuccessMakeOrderView.as_view(), name='order'),
    url(r'^update_quantity_product/(?P<pk>[\d]+)/$', UpdateQuantityProductView.as_view(), name='update_quantity_product'),
]

templates/base.html
{% spaceless %}
    <!DOCTYPE html>
    <html lang="en" {% block ngApp %}ng-app="clavutich"{% endblock %}>
    <head>
        {% load staticfiles %}
        {% load mptt_tags %}
        {% load thumbnail %}

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        {% if debug %}
            <link rel="stylesheet" type="text/css" href="{% static 'bower_components/font-awesome/css/font-awesome.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static "djangular/css/styles.css" %}" />
            <link rel="stylesheet" type="text/css" href="{% static "src/css/bootstrap.css" %}">
            <link rel="stylesheet" type="text/css" href="{% static "src/highslide/highslide.css" %}" />
            <link rel="stylesheet" type="text/css" href="{% static "src/css/shop-homepage.css" %}">
        {% endif %}

        <title>{% block title %}Clavutich{% endblock %}</title>
        <meta name="description" content="{% block meta_description %}{% endblock %}">
        <meta name="meta_keywords" content="{% block meta_keywords %}{% endblock %}">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    </head>
    <body>
    {% block header %}
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand logo" href="{% url 'home' %}"></a>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'about' %}">О нас</a></li>
                        <li><a href="{% url 'contacts' %}">Контакты</a></li>
                        <li><a href="{% url 'write_to_us' %}">Связаться с нами</a></li>

                        {% if nodes %}
                            <li>
                                <ul class="nav navbar-nav">
                                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Каталог <b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            {% recursetree nodes %}
                                                {% with title=node.title|lower|capfirst|truncatechars:30 url=node.get_absolute_url %}
                                                    {% if not node.is_leaf_node %}
                                                        <li class="dropdown dropdown-submenu">
                                                            <a href="{{ url }}" class="dropdown-toggle">
                                                                {{ title }}
                                                            </a>
                                                            <ul class="dropdown-menu">
                                                                {{ children }}
                                                            </ul>
                                                        </li>
                                                    {% else %}
                                                        <li>
                                                            <a href="{{ url }}">
                                                                {{ title }}
                                                            </a>
                                                        </li>
                                                    {% endif %}
                                                {% endwith %}
                                            {% endrecursetree %}
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Корзина <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'easy_cart:show' %}">Просмотреть корзину</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="{% url 'easy_cart:order' %}">Сделать заказ</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    {% endblock %}

    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                {% block breadcrumbs %}{% endblock %}
            </div>

            {% block main %}
                <div class="col-xs-12">
                    <h1>Clavutich</h1>
                    <div class="col-lg-12">
                        <h3>Последние товары</h3>
                    </div>

                    <div class="row text-center">
                        {% for product in products %}
                            <div class="col-md-3 col-sm-6 hero-feature">
                                <div class="thumbnail">
                                    {% with title=product.title|lower|capfirst %}
                                        <a href="{{ product.get_absolute_url }}">
                                            <img src="{% thumbnail product.image 300x150 crop %}" class="img-responsive img-rounded" title="{{ title }}" alt="{{ title }}">
                                        </a>
                                        <div class="caption">
                                            <a href="{{ product.get_absolute_url }}">
                                                <h4>{{ title|truncatechars:30 }}</h4>
                                            </a>
                                            <p>{{ product.description|striptags|safe|truncatechars:50 }}</p>
                                            <p>
                                                <a href="{{ product.get_absolute_url }}" class="btn btn-default">Детальнее</a>
                                            </p>
                                        </div>
                                    {% endwith %}
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endblock %}
        </div>
    </div>

    {% block footer %}
        <div class="container">
            <hr>
            <footer>
                <div class="row">
                    <div class="col-lg-12">
                        {% with start_year='2015' %}
                            {% now "Y" as current_year %}
                            <p>Copyright &copy; clavutich.com.ua {{ start_year }}
                            {% if current_year != start_year %}
                                - {{ current_year }}
                            {% endif %}
                        {% endwith %}
                        </p>
                    </div>
                </div>
            </footer>
        </div>
    {% endblock %}

    {% if debug %}
        <script src="{% static 'bower_components/jquery/dist/jquery.js' %}"></script>
        <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.js' %}"></script>
        <script src="{% static "bower_components/angular/angular.js" %}" type="text/javascript"></script>
        <script src="{% static "bower_components/angular-animate/angular-animate.min.js" %}" type="text/javascript"></script>
        <script src="{% static "bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js" %}" type="text/javascript"></script>
        <script src="{% static "bower_components/angular-scroll/angular-scroll.min.js" %}" type="text/javascript"></script>
        <script src="{% static "bower_components/bootstrap-checkbox/dist/js/bootstrap-checkbox.js" %}" type="text/javascript"></script>

        <script src="{% static "djangular/js/django-angular.js" %}" type="text/javascript"></script>
        <script src="{% static "src/js/ng-django-forms.js" %}" type="text/javascript"></script>

        <script src="{% static "src/highslide/highslide-with-gallery.js" %}" type="text/javascript"></script>
        <script src="{% static "src/js/custom.js" %}" type="text/javascript"></script>
        <script src="{% static "src/js/clavutich/src/js/script.js" %}" type="text/javascript"></script>
    {% else %}
        <script async src="{% static "build/js/script.min.js" %}"></script>
    {% endif %}
    </body>
    {%  if not debug %}
        <link rel="stylesheet" type="text/css" href="{% static "build/css/style.min.css" %}">
    {% endif %}
    </html>
{% endspaceless %}

templates/left_bar.html
{% load mptt_tags %}

<div class="col-md-3">
    <p class="lead">Каталог</p>
    <nav class="navbar">
        <div id="None">
            <div class="list-group panel">
                {% recursetree nodes %}
                    {% with title=node.title|lower|capfirst|truncatechars:60 url=node.get_absolute_url %}
                        {% if not node.is_leaf_node %}
                            <a href="#cat_{{ node.pk }}" data-toggle="collapse" class="list-group-item {% ifequal category.slug node.slug %}list-group-item-default{% endifequal %}" data-parent="#cat_{{ node.parent.pk }}">
                                {{ title }} <i class="fa fa-caret-down"></i>
                            </a>

                            <div class="collapse list-group-submenu{% if node in category.get_ancestors %} in{% endif %}" aria-labelledby="cat_{{ node.pk }}" id="cat_{{ node.pk }}">
                                {{ children }}
                            </div>
                        {% else %}
                            <a href="{{ url }}" class="list-group-item {% ifequal category.slug node.slug %}list-group-item-default{% endifequal %}" data-parent="#cat_{{ node.parent.pk }}">
                                {{ title }}
                            </a>
                        {% endif %}
                    {% endwith %}
                {% endrecursetree %}
            </div>
        </div>
    </nav>
</div>

templates/write_to_us.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Связаться с нами{% endblock %}

{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li><a href="/">Главная</a></li>

        <li class="active">Связаться с нами</li>
    </ol>
{% endblock %}

{% block main %}
    <div class="col-xs-12" id="form" ng-controller="MyFormCtrl" ng-cloak>
        <h1>Связаться с нами</h1>

        <script type="text/ng-template" id="alert.html">
            <div class="alert" style="background-color:#fa39c3;color:white" role="alert">
                <div ng-transclude></div>
            </div>
        </script>

        {% verbatim alerts %}
            <div id="alerts">
                <alert ng-repeat="alert in alerts" type="{{alert.type}}" close="closeAlert($index)">{{alert.msg}}</alert>
            </div>
        {% endverbatim alerts %}

        <form name="{{ form.form_name }}" method="post" novalidate="novalidate" action="svyazatsya-s-nami/">
            {% csrf_token %}
            {{ form.as_div }}
            <div class="cBtn" >
                <button id="comment_form" type="button" class="btn btn-primary" ng-disabled="disabled_form" ng-click="submit()">
                    <i class="fa fa-share"></i>
                    Отправить сообщение
                </button>
            </div>
        </form>
    </div>
{% endblock %}